defaults:
  - experiment: cnn_baseline
  - training: default
  - data: vlsp_2016
  - model: cnn
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# Global settings
seed: 42
device: "cuda"
num_workers: 8

# Logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Experiment tracking
wandb:
  project: "vietnamese-sentiment-analysis"
  entity: null  # Set your W&B entity
  log_model: true
  save_code: true